// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OportunityApi.Data;

#nullable disable

namespace OportunityApi.Migrations
{
    [DbContext(typeof(OportunityApiContext))]
    partial class OportunityApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Oportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ErrorsQty")
                        .HasColumnType("int");

                    b.Property<int>("HoursOff")
                        .HasColumnType("int");

                    b.Property<int>("HoursQty")
                        .HasColumnType("int");

                    b.Property<long>("LearningLevel")
                        .HasColumnType("bigint");

                    b.Property<string>("OutbreakLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SleepingHours")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Oportunity");
                });
#pragma warning restore 612, 618
        }
    }
}
